import { CardLayerConfig, CardSectionData, CardTypeKey } from "./cardData";

/**
 * Official Backside Presets & Layer Configurations
 * Calibrated to authentic government standards and institutional specifications.
 */

// 1. PAN Card Backside Default Layers
export const PAN_BACK_LAYERS: CardLayerConfig[] = [
  {
    id: "pan_back_title",
    name: "Income Tax Dept Title",
    type: "text",
    x: 50.0,
    y: 11.0,
    fontSize: 22,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    textAlign: "center",
    visible: true,
    dataKey: "cardTitle",
    uppercase: true,
  },
  {
    id: "pan_back_subtitle",
    name: "Hindi Subtitle",
    type: "text",
    x: 50.0,
    y: 17.5,
    fontSize: 16,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    textAlign: "center",
    visible: true,
    dataKey: "cardTitleHi",
  },
  {
    id: "pan_back_inst1",
    name: "Legal Notice 1 (English)",
    type: "text",
    x: 6.0,
    y: 28.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
  },
  {
    id: "pan_back_inst2",
    name: "Return Notice 2 (English)",
    type: "text",
    x: 6.0,
    y: 36.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#1e293b",
    textAlign: "left",
    visible: true,
  },
  {
    id: "pan_back_inst3",
    name: "Penal Provision 3 (English)",
    type: "text",
    x: 6.0,
    y: 45.0,
    fontSize: 12,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#334155",
    textAlign: "left",
    visible: true,
  },
  {
    id: "pan_back_inst4_hi",
    name: "Notice 4 (Hindi)",
    type: "text",
    x: 6.0,
    y: 54.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#1e293b",
    textAlign: "left",
    visible: true,
  },
  {
    id: "pan_back_barcode",
    name: "PAN Barcode",
    type: "barcode",
    x: 25.0,
    y: 66.0,
    width: 50.0,
    height: 14.0,
    visible: true,
  },
  {
    id: "pan_back_helpline",
    name: "Helpline & Website",
    type: "text",
    x: 50.0,
    y: 89.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#475569",
    textAlign: "center",
    visible: true,
  },
];

// 2. Aadhaar Card Backside Default Layers (Address & QR)
export const AADHAAR_BACK_LAYERS: CardLayerConfig[] = [
  {
    id: "aadhaar_back_header",
    name: "UIDAI Header (Bilingual)",
    type: "text",
    x: 6.0,
    y: 8.0,
    fontSize: 18,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#b91c1c",
    textAlign: "left",
    visible: true,
    dataKey: "cardTitleHi",
  },
  {
    id: "aadhaar_back_sub",
    name: "Unique Identification Authority",
    type: "text",
    x: 6.0,
    y: 13.5,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    textAlign: "left",
    visible: true,
    dataKey: "subtitle",
  },
  {
    id: "aadhaar_back_addr_hi",
    name: "पता / Address (Hindi)",
    type: "text",
    x: 6.0,
    y: 25.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
    dataKey: "addressHi",
  },
  {
    id: "aadhaar_back_addr_en",
    name: "Address (English)",
    type: "text",
    x: 6.0,
    y: 44.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
    dataKey: "addressEn",
  },
  {
    id: "aadhaar_back_pincode",
    name: "PIN Code",
    type: "text",
    x: 6.0,
    y: 64.0,
    fontSize: 15,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e293b",
    prefix: "PIN: ",
    textAlign: "left",
    visible: true,
    dataKey: "pinCode",
  },
  {
    id: "aadhaar_back_qr",
    name: "UIDAI Secure 2D Barcode",
    type: "qr",
    x: 72.0,
    y: 25.0,
    width: 22.0,
    height: 35.0,
    visible: true,
  },
  {
    id: "aadhaar_back_id",
    name: "12-Digit Aadhaar Number",
    type: "text",
    x: 50.0,
    y: 78.0,
    fontSize: 32,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#047857",
    letterSpacing: "0.2em",
    textAlign: "center",
    visible: true,
    dataKey: "idNumber",
  },
  {
    id: "aadhaar_back_help",
    name: "UIDAI Help 1947 & Portal",
    type: "text",
    x: 50.0,
    y: 91.0,
    fontSize: 12,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#475569",
    textAlign: "center",
    visible: true,
  },
];

// 3. Driving License Backside Default Layers
export const DL_BACK_LAYERS: CardLayerConfig[] = [
  {
    id: "dl_back_cov_header",
    name: "Vehicle Authorization Header",
    type: "text",
    x: 6.0,
    y: 10.0,
    fontSize: 16,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    textAlign: "left",
    visible: true,
  },
  {
    id: "dl_back_cov_table",
    name: "COV Class Table (MCWG / LMV)",
    type: "text",
    x: 6.0,
    y: 22.0,
    fontSize: 14,
    fontFamily: "'Share Tech Mono', monospace",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
  },
  {
    id: "dl_back_address_label",
    name: "Residential Address Label",
    type: "text",
    x: 6.0,
    y: 44.0,
    fontSize: 12,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#475569",
    prefix: "RESIDENTIAL ADDRESS / स्थायी पता:",
    textAlign: "left",
    visible: true,
  },
  {
    id: "dl_back_address",
    name: "Full Residential Address",
    type: "text",
    x: 6.0,
    y: 52.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
    dataKey: "addressEn",
  },
  {
    id: "dl_back_rto_authority",
    name: "Issuing Authority & Seal",
    type: "text",
    x: 6.0,
    y: 72.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e293b",
    prefix: "ISSUED BY: ",
    textAlign: "left",
    visible: true,
  },
  {
    id: "dl_back_donor",
    name: "Organ Donor Status",
    type: "text",
    x: 6.0,
    y: 80.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#dc2626",
    prefix: "ORGAN DONOR: YES | BLOOD GROUP: ",
    textAlign: "left",
    visible: true,
    dataKey: "bloodGroup",
  },
  {
    id: "dl_back_barcode",
    name: "DL Serial Barcode",
    type: "barcode",
    x: 55.0,
    y: 72.0,
    width: 38.0,
    height: 14.0,
    visible: true,
  },
];

// 4. Voter ID Backside Default Layers
export const VOTER_BACK_LAYERS: CardLayerConfig[] = [
  {
    id: "voter_back_header",
    name: "Election Commission Header",
    type: "text",
    x: 50.0,
    y: 10.0,
    fontSize: 18,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    textAlign: "center",
    visible: true,
    dataKey: "cardTitle",
  },
  {
    id: "voter_back_addr_label",
    name: "Address Header",
    type: "text",
    x: 6.0,
    y: 22.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#475569",
    prefix: "ELECTOR ADDRESS / निर्वाचक का पता:",
    textAlign: "left",
    visible: true,
  },
  {
    id: "voter_back_addr",
    name: "Elector Full Address",
    type: "text",
    x: 6.0,
    y: 30.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#0f172a",
    textAlign: "left",
    visible: true,
    dataKey: "addressEn",
  },
  {
    id: "voter_back_ac",
    name: "Assembly Constituency",
    type: "text",
    x: 6.0,
    y: 50.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#0f172a",
    prefix: "AC NO. & NAME: 12 - CHANDNI CHOWK",
    textAlign: "left",
    visible: true,
  },
  {
    id: "voter_back_pc",
    name: "Parliamentary Constituency",
    type: "text",
    x: 6.0,
    y: 58.0,
    fontSize: 14,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#0f172a",
    prefix: "PC NO. & NAME: 01 - CHANDNI CHOWK",
    textAlign: "left",
    visible: true,
  },
  {
    id: "voter_back_ero",
    name: "ERO Signature & Date",
    type: "text",
    x: 6.0,
    y: 78.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#334155",
    prefix: "ELECTORAL REGISTRATION OFFICER",
    textAlign: "left",
    visible: true,
  },
  {
    id: "voter_back_qr",
    name: "ECI 2D QR Code",
    type: "qr",
    x: 74.0,
    y: 60.0,
    width: 20.0,
    height: 32.0,
    visible: true,
  },
];

// 5. Student / Institutional / Employee / Loyalty / Library Backside Default Layers
export const INSTITUTIONAL_BACK_LAYERS: CardLayerConfig[] = [
  {
    id: "inst_back_stripe",
    name: "Magnetic Stripe",
    type: "barcode", // renders magnetic stripe bar
    x: 0.0,
    y: 0.0,
    width: 100.0,
    height: 18.0,
    visible: true,
  },
  {
    id: "inst_back_terms_title",
    name: "Terms & Conditions Header",
    type: "text",
    x: 6.0,
    y: 28.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#1e3a8a",
    prefix: "TERMS OF ISSUANCE & CARDHOLDER AGREEMENT",
    textAlign: "left",
    visible: true,
  },
  {
    id: "inst_back_terms_1",
    name: "Condition 1 (Non-Transferable)",
    type: "text",
    x: 6.0,
    y: 36.0,
    fontSize: 11,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#334155",
    prefix: "• This card remains the official property of the issuing organization.",
    textAlign: "left",
    visible: true,
  },
  {
    id: "inst_back_terms_2",
    name: "Condition 2 (Loss Reporting)",
    type: "text",
    x: 6.0,
    y: 44.0,
    fontSize: 11,
    fontFamily: "'Arial-Custom-Regular', Arial, sans-serif",
    color: "#334155",
    prefix: "• Report loss or theft immediately to Security or Card Services.",
    textAlign: "left",
    visible: true,
  },
  {
    id: "inst_back_emergency",
    name: "Emergency Contact",
    type: "text",
    x: 6.0,
    y: 56.0,
    fontSize: 13,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#dc2626",
    prefix: "24/7 CAMPUS EMERGENCY HELPLINE: ",
    textAlign: "left",
    visible: true,
    dataKey: "emergencyContact",
  },
  {
    id: "inst_back_barcode",
    name: "Turnstile / Library Barcode",
    type: "barcode",
    x: 6.0,
    y: 68.0,
    width: 48.0,
    height: 14.0,
    visible: true,
  },
  {
    id: "inst_back_sign_label",
    name: "Authorized Signatory",
    type: "text",
    x: 75.0,
    y: 84.0,
    fontSize: 11,
    fontFamily: "'Arial-Custom-Bold', Arial, sans-serif",
    color: "#475569",
    prefix: "AUTHORIZED SIGNATURE",
    textAlign: "center",
    visible: true,
  },
  {
    id: "inst_back_signature",
    name: "Dean / HR Signature",
    type: "signature",
    x: 64.0,
    y: 66.0,
    width: 25.0,
    height: 16.0,
    visible: true,
  },
];

/**
 * Returns official backside layers for any document preset
 */
export function getOfficialBackPresetLayers(cardType: CardTypeKey): CardLayerConfig[] {
  switch (cardType) {
    case "pan-latest":
      return JSON.parse(JSON.stringify(PAN_BACK_LAYERS));
    case "aadhaar-front":
    case "aadhaar-back":
      return JSON.parse(JSON.stringify(AADHAAR_BACK_LAYERS));
    case "driving-license":
      return JSON.parse(JSON.stringify(DL_BACK_LAYERS));
    case "voter-id":
      return JSON.parse(JSON.stringify(VOTER_BACK_LAYERS));
    case "student-card":
    case "employee-card":
    case "loyalty-card":
    case "library-card":
    default:
      return JSON.parse(JSON.stringify(INSTITUTIONAL_BACK_LAYERS));
  }
}
